---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: pydio/cells
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [pydiocells docs](https://pydio.com/en/docs/developer-guide/cells-start) (and other pages) for more details.
# @default -- See below
env:
  #CELLS_EXTERNAL=https://FQDN
  CELLS_BIND: 0.0.0.0:8080
  #CELLS_NO_TLS
  CELLS_WORKING_DIR: /var/cells
  # Automated installation; see below
  #CELLS_INSTALL_YAML: /config/install-conf.yaml

# Configuration: example- https://github.com/pydio/cells/blob/master/tools/docker/compose/multibind/install-conf.yml
# Other values here: https://pydio.com/en/docs/developer-guide/post-ainstallcheck
# Was not able to get this to work; may be easier to perform initial configuration via web interface and env variables for bind/external URLs
configmap:
  config:
    enabled: false
    data:
      install-conf.yaml: |
        proxyconfig:
          binds:
            - 0.0.0.0:8080
          reverseproxyurl: https://FQDN
          tlsconfig:
            selfsigned:
              hostnames:
                - localhost
        # WebUI Admin definition
        frontendlogin: admin
        frontendpassword: admin
        # # DB connection
        dbconnectiontype: tcp
        # TODO: check this hostname
        dbtcphostname: pydio-mariadb
        dbtcpport: 3306
        dbtcpname: pydiocells
        dbtcpuser: pydio
        dbtcppassword: ChangeMe!

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false

# -- Enable and configure mariadb database subchart under this key.
#    See [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb) for more details.
# @default -- See values.yaml
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: pydiocells
    username: pydio
    password: ChangeMe!
  primary:
    persistence:
      enabled: false

# -- Enable and configure postgresql subchart under this key.
#    See [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) for more details.
# @default -- See values.yaml
# TODO: the above non-interactive install-conf.yaml example will need to be updated for postgres
postgresql:
  enabled: false
  #auth:
  #  username: pydiocells
  #  password: pydiocells
  #  database: pydiocells
  # persistence:
  #   enabled: false
