#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/babybuddy
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [babybuddy docs](https://docs.baby-buddy.net/setup/configuration/) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /config

# -- Enable and configure mariadb database subchart under this key.
#    See [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb) for more details.
# @default -- See values.yaml
mariadb:
  enabled: false
  #architecture: standalone
  #auth:
  #  database: babybuddy
  #  username: babybuddy
  #  password: babybuddy
  #primary:
  #  persistence:
  #    enabled: false

# -- Enable and configure postgresql subchart under this key.
#    See [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) for more details.
# @default -- See values.yaml
postgresql:
  enabled: false
  #auth:
  #  username: babybuddy
  #  password: babybuddy
  #  database: babybuddy
  # persistence:
  #   enabled: false
